### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './outputLOCAL_._projects_PROJECTNAME.json

### ISSUE THREAD

**Issue by claudijd** [BuffaloWill/gumbler#8]
Ran into this when playing around, I'll debug and send a PR when I sort it out, but wanted to share anyways.

**Comment by claudijd** [comment]
```
python gumbler.py -o server -x "./output"
Traceback (most recent call last):
  File "gumbler.py", line 39, in <module>
    server.load_projects()
  File "/PATH/gumbler/webserver/server.py", line 20, in load_projects
    x = json.load(open(dira+file))
IOError: [Errno 2] No such file or directory: './outputLOCAL_._projects_PROJECTNAME.json'
```

**Comment by claudijd** [comment]
The project JSON file was named this when run on Mac...

LOCAL_._projects_PROJECTNAME

Simply renaming the file and adding a slash to the -x string did the trick....

```
python gumbler.py -o server -x "./output/"
0
 * Running on http://127.0.0.1:5000/
127.0.0.1 - - [18/Jul/2017 14:23:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2017 14:23:54] "GET /favicon.ico HTTP/1.1" 404 -
```

However, after doing so, I got zero projects in the list.

Going to retry this using Ubuntu and see if it's an OS specific issue.

**Comment by BuffaloWill** [comment]
If gumbler doesn't find any issues with the project, it will not appear in the server list. Check to make sure the json file has data, please.

**Comment by claudijd** [comment]
Nope, empty, this is probably why then.  So it's isolated to that weird path creation on Mac, which was not consumable by the server.

**Comment by claudijd** [comment]
Re-run this under docker ubuntu:latest and it seemed to work alright.

Repro steps...

```
apt-get update
apt-get install git python-pip curl
mkdir code
cd code
git clone https://github.com/BuffaloWill/gumbler.git
cd gumbler
pip install -r requirements.txt
pip install requests
mkdir projects
cd projects
git clone https://github.com/OWNER/REPO.git
cd ..
python gumbler.py -r "./projects/REPO" -a -p "OWNER/REPO"
```
That successfully produced REPO.json, so it's a Mac thing.

**Comment by n00py** [comment]
Also happened to me.

 $python gumbler.py -o server -x "./output"

    IOError: [Errno 2] No such file or directory: './outputREPO.json'

No slash in between output and the repo name 

Linux parrot 4.8.0-parrot-amd64

**Comment by claudijd** [comment]
We should probably just make sure that any argument to -x has a "/" or has a "/" added automagically to prevent this from happening in the future
